config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :devices do
    get :credentials, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :device
end

app/models/device.rb
class Device < ApplicationRecord
  
  before_validation :generate_reference
  before_validation :generate_password
  # after_create_commit { broadcast_append_to "devices" }
  # after_destroy_commit { broadcast_remove_to "devices" }
  belongs_to :user, foreign_key: 'user_id'
  validates :name, presence: true, uniqueness: true


  def generate_reference
    self.reference = SecureRandom.hex(8)
    puts "self.reference = #{self.reference}"
  end

  def generate_password
    self.password =  SecureRandom.hex(10)
    puts "self.password = #{self.password}"
  end
end

app/models/home.rb
class Home < ApplicationRecord
  
end

app/models/user.rb
#virtaul fields => password and password_confirmation and thy both string fields
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :devices
  
  def user_name
    self.email.split("@")[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_device
  #after_action :update_device_online_status

  before_action :set_last_online, if: proc { @current_device && (session[:last_online] == nil || session[:last_online] < 15.minutes.ago) }

  def set_current_device
    if session[:device_id]
      @current_device = Device.find(session[:device_id])
    end
  end

  private
  # def update_device_online_status
  #   if @current_device && @current_device.last_online.to_i < 2.minutes.ago.to_i
  #     @current_device.update(is_active: true)
  #   end
  # end

  def set_last_online
    @current_device.update_attribute(:last_online, Time.current)
    session[:last_online] = Time.current
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  after_action :update_is_credentials_showed, only: [:credentials]
  def index
    @devices = Device.where(user_id: current_user.id).order(id: :desc)
  end
  
  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)
    @device.user_id = current_user.id
    if @device.save
      #show credentials once with turbo
      respond_to do |format|
        #format.turbo_stream { render turbo_stream: turbo_stream.prepend('devices', partial: 'devices/devices_list', locals: {device: @device}) }
        format.html { redirect_to devices_path }
        format.js
      end
    else
      render :new
    end
  end

  def credentials
    set_device
    respond_to do |format|
      format.js
    end
  end

  def destroy
    set_device
    @device.destroy
    respond_to do |format|
      #format.turbo_stream { render turbo_stream: turbo_stream.remove(@device)}
      format.html { redirect_to devices_path }
    end
  end

  private
  def device_params
    params.require(:device).permit(:name, :notes)
  end

  def set_device
    @device = Device.find(params[:id])
  end

  def update_is_credentials_showed
    @device.update(is_credentials_showed: true)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if @current_device
      @devices = Device.where("last_online > ?", 5.minutes.ago).order(id: :desc)
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @device = Device.new
  end

  def create
    @device = Device.find_by(reference: params[:device][:reference])
    if @device && @device.authenticate(params[:device][:password])
      session[:device_id] = @device.id
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @device = Device.new
  end

  def create
    @device = Device.find_by(reference: params[:reference])
    if @device && @device.password = params[:password]#@device.authenticate(params[:password])
      session[:device_id] = @device.id
      redirect_to root_path, notice: "Welcome Dear Device!"
    else
      render :new
    end
  end

  def destroy
    #burada boolean is_active false yapılabilir
    session[:device_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/devices/_device.html.erb
<tr>
  <td><%= device.name %></td>
  <td><%= device.notes %></td>
  <% if device.is_credentials_showed %>
    <td></td>
  <% else %>
    <td><%= link_to 'Show Credentials', credentials_device_path(device), remote: true %></td>
  <% end %>
  <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <%#= link_to 'Destroy', device, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
</tr>

<script>
  
</script>

app/views/devices/_device_form.html.erb
<div class="card card-custom gutter-b">
  <div class="card-body">
    <%= simple_form_for @device, html: { class: 'horizontal-form' } do |f| %>
      <%= f.error :base, :error_method => :to_sentence, class: "alert alert-danger" %>
        <% if @device.errors.present? %>
          <div class="alert alert-custom alert-outline-2x alert-outline-danger fade show mb-5">
            <div class="alert-icon"><i class="far fa-exclamation-circle"></i></div>
            <p class="alert-text font-weight-bold"><%= @device.errors.full_messages.join("; ") %></p>
          </div>
        <% end %>
      
      <div class="mb-3">
        <%= f.input :name, label: false, as: :text, class: "form-group", placeholder: "Name of Device", input_html: { rows: 1 } %>
      </div>
      <div class="mb-3">
        <%= f.input :notes, label: false, as: :text, class: "form-group", placeholder: "Device Notes", input_html: { rows: 2 } %>
      </div>
      <div class="separator separator-solid my-4"></div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6">
          <%= f.button :submit, "Generate Device", class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/devices/_devices_list.html.erb
<div class="table-responsive table-truncate mt-8 min-h-300px">
  <table id="active_devices_list_table" class="table table-vertical-center">
    <thead>
      <tr class="text-dark text-uppercase">
        <th> Device Name </th>
        <th> Description </th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody id="active_devices_list_tbody">
      <%= render partial: "devices/device", collection: @devices, as: :device %>
    </tbody>
  </table>
</div>

app/views/devices/_online_device.erb
<%#= content_tag :tr, id: dom_id(online_device) do %>
  <tr>
    <td><i style="color:green" class="fa-solid fa-globe"></i></td>
    <td><%= online_device.name %></td>
    <td><%= online_device.notes %></td>
  </tr>
<%# end %>

app/views/devices/_online_devices_list.html.erb
<div class="table-responsive table-truncate mt-8 min-h-300px">
  <table id="active_devices_list_table" class="table table-vertical-center">
    <thead>
      <tr class="text-dark text-uppercase">
        <th></th>
        <th> Device Name </th>
        <th> Description </th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "devices/online_device", collection: devices, as: :online_device %>
    </tbody>
  </table>
</div>

app/views/devices/credentials.js.erb
<% unless @device.is_credentials_showed %>
  swal("Credentials", "Reference <%= @device.reference %>\nPassword <%= @device.password %>", "success");
<% else %>
  swal("You already seen this", "", "error");  
<% end %>

app/views/devices/index.html.erb
<%
=begin%>
 <%= turbo_stream_from "devices" %>
<%= turbo_frame_tag "devices" do %> 
<%
=end%>
  <%= render "devices/devices_list" %>
<%# end %>

app/views/devices/new.html.erb
<div class="row">
  <div class="col-md-6">
    <%#= turbo_frame_tag "modal" do %>
      <%= render "devices/device_form", device: @device %>
    <%# end %>
  </div>
</div>

app/views/home/_online_devices_list.html.erb
<div class="table-responsive table-truncate mt-8 min-h-300px">
  <table id="active_devices_list_table" class="table table-vertical-center">
    <thead>
      <tr class="text-dark text-uppercase">
        <th></th>
        <th> Device Name </th>
        <th> Description </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><i style="color:green" class="fa-solid fa-globe"></i></td>
        <td><%= online_device.name %></td>
        <td><%= online_device.notes %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<div class="align-items-center justify-content-center">
  <% if @current_device %>
    <h1>Welcome <span style="color:blue;"><%= @current_device.name %></span> as i can see, you are a device.</h1>
    <div class="row">
      <%= render partial: "devices/online_devices_list", locals: { devices: @devices } %>
    </div>
  <% elsif user_signed_in? %>
    <h1>Welcome <%= current_user.user_name %> you smell like a human.</h1>
    <p> If you wanna do something, you can do it here: </p>
    <p> <%= link_to "Create a new device", new_device_path %> </p>
    <p> <%= link_to "See your devices", devices_path %> </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveDevicesFinalv2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js" integrity="sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%#= turbo_frame_tag "shared/modal" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <div class="alert alert-info mt-4" role="alert">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-warning mt-4" role="alert">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal" data-action="keyup@document->modal#handleKeyup">
    <div class="modal-background" data-action="click->modal#close"></div>

    <div class="modal-styles-and-stuff">
      <button data-action="modal#close">X</button>

      <%= turbo_frame_tag "modal-body" do %>
        <%= yield %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-blue bg-blue">
  <a class="navbar-brand" href="#">Active Devices</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fas fa-home p-2">Home</i>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            <i class="fas fa-sign-out-alt p-2">Logout</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_device_path, class: "nav-link" do %> <%#data: {turbo_frame: 'modal'}%>
            <i class="fas fa-laptop p-2">Add Device</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to sign_in_path, class: "nav-link" do %>
              <i class="fas fa-laptop p-2">Login as Device</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to devices_path, class: "nav-link" do %>
              <i class="fas fa-laptop p-2">See Devices</i>
          <% end %>
      <% elsif @current_device %>
        <li class="nav-item">
          <%= link_to logout_path, method: :delete, class: "nav-link" do %>
            <i class="fas fa-sign-out-alt p-2">Logout</i>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fas fa-sign-in-alt p-2">Login</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to sign_in_path, class: "nav-link" do %>
              <i class="fas fa-laptop p-2">Login as Device</i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
              <i class="fas fa-user-plus p-2">Register (User)</i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>